model: 'iptv3'
## parameters for plain
scale: 2
rgb_range: 255
colors: 3
m_elan: 8
c_elan: 24
n_share: 1
r_expand: 1
deploy: False
act_type: 'relu'
window_sizes: [8,8]
pretrain:

patch_size: 512
batch_size: 64
data_repeat: 80
data_augment: 1

epochs: 1000
lr: 0.0002
decays: [250, 400, 450, 475, 500]
gamma: 0.5
log_every: 100
test_every: 10
log_path: "./experiments"
log_name:

## hardware specification
gpu_ids: [0,1,2,3,4,5,6,7]
threads: 1

## data specification
data_path: '/home/ma-user/modelarts/user-job-dir/LIPT/dataset'
data_test_path: '/home/ma-user/modelarts/user-job-dir/LIPT/Benchmark_SR/'
eval_sets: ['Set5', 'Set14', 'B100', 'Urban100', 'Manga109']